import {pipeline,env} from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2";
env.allowLocalModels=false;env.useBrowserCache=true;
const $=id=>document.getElementById(id);
const videoInput=$("videoInput"),video=$("video"),overlay=$("captionOverlay"),track=$("captionsTrack"),seek=$("seek");
const status=$("status"),generateBtn=$("generateCaptions"),stylesGrid=$("stylesGrid"),progressBar=$("progressBar"),progressText=$("progressText");
const wordsRange=$("wordsPerCaption"),wordCount=$("wordCount"),fontSize=$("fontSize"),fontSizeValue=$("fontSizeValue"),position=$("captionPosition");
let captions=[],currentCue=-1,model=null;
const presets=[
["Neon Glow","#d7ff34","glow"],["Clean Pop","#fff","pop"],["Orange Bounce","#ff8a00","bounce"],["Purple Slide","#b46cff","slide"],["Ice Blue","#63dcff","pop"],["Red Impact","#ff4b4b","bounce"],["Gold","#ffd24d","zoom"],["Green Punch","#4dff9a","bounce"],["Electric Neon","#37f5ff","neon"],["Hot Pink","#ff4fba","glow"],["Karaoke Gold","#ffd24d","glow"],["Typewriter","#fff","type"],["Glitch","#fff","glitch"],["Zoom Impact","#fff","zoom"],["White Bold","#fff","pop"],["Cinematic","#fff","glow"],["Blue Glow","#58a6ff","glow"],["Violet Neon","#c77dff","neon"],["Lime Punch","#b7ff00","bounce"],["Fire","#ff6b35","pop"],["Sky Pop","#70d6ff","pop"],["Rose Glow","#ff8fab","glow"],["Mono Minimal","#fff","pop"],["Cyber","#a8ffea","glitch"],["Dream","#d9b3ff","slide"],["Sunset","#ff9f1c","bounce"],["Ice","#bde0fe","zoom"],["Loud Lyrics","#fff","bounce"],["Soft Subtitle","#fff","pop"],["Electric Purple","#8b5cf6","neon"],["Viral Pop","#fff","pop"],["Word Zoom","#f8f9fa","zoom"],["Retro","#ffd166","type"],["Nightclub","#00f5d4","glitch"],["Street","#f1f1f1","bounce"],["Luxury","#f8e7b0","glow"],["Reel Flash","#fff","zoom"],["Beat Glow","#00ff9d","glow"],["Kinetic","#fff","slide"],["Comic","#ffea00","bounce"],["Deep Red","#ff304f","glow"]
];
let selected=presets[0];
function stat(t){status.textContent="● "+t}
function fmt(t){if(!isFinite(t))return"00:00.0";return String(Math.floor(t/60)).padStart(2,"0")+":"+String(Math.floor(t%60)).padStart(2,"0")+"."+Math.floor((t%1)*10)}
function renderPresets(){stylesGrid.innerHTML="";$("presetCount").textContent=presets.length+" presets";presets.forEach((p,i)=>{let b=document.createElement("button");b.className="style "+(i?"":"active");b.textContent="Aa Lyrics";b.style.color=p[1];b.style.textShadow=`0 0 12px ${p[1]}`;b.title=p[0];b.onclick=()=>{selected=p;document.querySelectorAll(".style").forEach(x=>x.classList.remove("active"));b.classList.add("active");refresh(true)};stylesGrid.appendChild(b)})}
function setVideo(f){if(!f)return;video.src=URL.createObjectURL(f);$("emptyState").style.display="none";captions=[];track.innerHTML="<p>Generate captions to see the timeline.</p>";overlay.textContent="";stat("Video loaded")}
$("chooseVideo").onclick=()=>videoInput.click();$("uploadTop").onclick=()=>videoInput.click();videoInput.onchange=()=>setVideo(videoInput.files[0]);
$("dropZone").ondragover=e=>e.preventDefault();$("dropZone").ondrop=e=>{e.preventDefault();setVideo(e.dataTransfer.files[0])};
video.onloadedmetadata=()=>{$("duration").textContent=fmt(video.duration)};video.ontimeupdate=()=>{seek.value=video.duration?video.currentTime/video.duration*1000:0;$("currentTime").textContent=fmt(video.currentTime);refresh(false)};
$("playBtn").onclick=()=>video.paused?video.play():video.pause();video.onplay=()=>$("playBtn").textContent="❚❚";video.onpause=()=>$("playBtn").textContent="▶";seek.oninput=()=>video.currentTime=seek.value/1000*video.duration;
wordsRange.oninput=()=>wordCount.textContent=wordsRange.value;fontSize.oninput=()=>{fontSizeValue.textContent=fontSize.value;overlay.style.fontSize=fontSize.value+"px"};position.onchange=()=>{overlay.style.top=position.value==="top"?"9%":position.value==="center"?"45%":"auto";overlay.style.bottom=position.value==="bottom"?"9%":"auto"};
function refresh(force){let i=captions.findIndex(c=>video.currentTime>=c.start&&video.currentTime<c.end);if(i===currentCue&&!force)return;currentCue=i;let c=captions[i];if(!c){overlay.textContent="";return}overlay.className="caption-overlay "+selected[2];overlay.style.color=selected[1];overlay.style.fontSize=fontSize.value+"px";overlay.textContent=c.text;document.querySelectorAll(".cue").forEach(x=>x.classList.toggle("active",+x.dataset.i===i))}
function renderTrack(){track.innerHTML="";captions.forEach((c,i)=>{let e=document.createElement("div");e.className="cue";e.dataset.i=i;e.innerHTML="<b>"+esc(c.text)+"</b><span>"+fmt(c.start)+" - "+fmt(c.end)+"</span>";e.onclick=()=>{video.currentTime=c.start;video.play()};track.appendChild(e)})}
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
async function audio(file){let C=new(window.AudioContext||window.webkitAudioContext)(),b=await C.decodeAudioData(await file.arrayBuffer()),rate=16000,len=Math.min(b.duration,600)*rate,m=new Float32Array(Math.floor(len));for(let ch=0;ch<b.numberOfChannels;ch++){let d=b.getChannelData(ch);for(let i=0;i<m.length;i++)m[i]+=(d[Math.floor(i*b.sampleRate/rate)]||0)/b.numberOfChannels}return m}
async function getModel(){if(model)return model;progressText.textContent="Downloading Whisper model — first time only...";model=await pipeline("automatic-speech-recognition","Xenova/whisper-tiny",{dtype:"q8",progress_callback:p=>{if(typeof p.progress==="number"){progressBar.style.width=Math.round(p.progress)+"%";progressText.textContent="Model download "+Math.round(p.progress)+"%"}}});return model}
function chunks(ch,text){if(!ch?.length)return text?.trim()?[{text:text.trim(),start:0,end:Math.max(video.duration||5,1)}]:[];let o=[],g=[],lim=+wordsRange.value,s=null,e=null;for(let x of ch){let t=String(x.text||"").trim();if(!t)continue;let ts=x.timestamp||[0,0];if(s===null)s=+ts[0]||0;e=+ts[1]||s+.8;g.push(t);if(g.join(" ").split(/\s+/).length>=lim||/[.!?]$/.test(t)){o.push({text:g.join(" "),start:s,end:Math.max(e,s+.5)});g=[];s=null}}if(g.length)o.push({text:g.join(" "),start:s??0,end:Math.max(e??2,(s??0)+.5)});return o}
generateBtn.onclick=async()=>{let f=videoInput.files[0];if(!f)return stat("Pehle video upload karo");try{generateBtn.disabled=true;stat("Local AI model loading...");let m=await getModel();stat("Audio processing...");let a=await audio(f);stat("Captions generating...");let lang=$("language").value,r=await m(a,{chunk_length_s:30,stride_length_s:5,return_timestamps:true,task:"transcribe",...(lang==="hi"?{language:"hi"}:{})});captions=chunks(r.chunks,r.text);renderTrack();refresh(true);stat(captions.length+" captions generated!");progressText.textContent="Done — processed locally."}catch(e){console.error(e);stat("Caption failed: "+(e.message||"Browser processing failed"));progressText.textContent="Try Chrome/Edge and a shorter video."}finally{generateBtn.disabled=false}};
function dl(n,t,type){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click()}
function srt(t){let h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=Math.floor(t%60),ms=Math.floor(t%1*1000);return`${String(h).padStart(2,"0")}:${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")},${String(ms).padStart(3,"0")}`}
$("downloadSrt").onclick=()=>dl("captions.srt",captions.map((c,i)=>`${i+1}\n${srt(c.start)} --> ${srt(c.end)}\n${c.text}\n`).join("\n"),"text/plain");$("exportSrt").onclick=()=>$("downloadSrt").click();
$("downloadJson").onclick=()=>dl("caption-style.json",JSON.stringify({preset:selected[0],captions},null,2),"application/json");
renderPresets();stat("Waiting for video");
